### ISSUE TITLE
Duplicate option names (and help text)

### ISSUE THREAD

**Issue by Eonasdan** [BigBabay/AsyncConverter#11]
Thanks for making this plugin. I found an issue where your inspector options have the same text and it's a little confusing.

![image](https://cloud.githubusercontent.com/assets/1006516/26016859/c075c2c6-3734-11e7-8de0-d12ca56b334f.png)

![image](https://cloud.githubusercontent.com/assets/1006516/26017013/749a3c6e-3735-11e7-83b9-98a3b94dcf04.png)

**Comment by BigBabay** [comment]
Thanks. Fixed.
