### ISSUE TITLE
Don't check ConfigureAwait when using Fody ConfigureAwait weaver

### ISSUE THREAD

**Issue by cmeeren** [BigBabay/AsyncConverter#15]
Perhaps AsyncConverter could play nicely with [ConfigureAwait.Fody](https://github.com/distantcam/ConfigureAwait)?

* When `[assembly: Fody.ConfigureAwait(bool)]` is present, disable the analysis for that assembly.
* When `[Fody.ConfigureAwait(bool)]` is present on a class or method, disable the analysis for that class or method.

**Comment by BigBabay** [comment]
Hi, cmeeren.

I have added settings in new version 1.1.8. You may specify attribute to ignore suggestion ConfigureAwait in class and method. ReSharper=>Options=>Code Inspection=>Async Converter=>ConfigureAwait settings

**Comment by Pentagrade** [comment]
Is there any article or guidance on how this works? I'm unable to get this working
