### ISSUE TITLE
AsyncAwaitMayBeElidedHighlighting

### ISSUE THREAD

**Issue by ghost** [BigBabay/AsyncConverter#17]
AsyncAwaitMayBeElidedHighlighting feature wants to elide an await in an async void function, which does not make sense:
        public async void OnEvent()
        {
                await ExecuteStuffAsync();
        }

Also this await, which does not make sense also:
        public async Task SomeFuncAsync()
        {
            if (Foo())
                await BarAsync();
        }
as the result is not really what you want:
        public Task SomeFuncAsync()
        {
            if (Foo())
                return BarAsync();
        }

**Comment by BigBabay** [comment]
fix in  1.1.8.2.
