### ISSUE TITLE
Install completed with errors (R# 2017.2)

### ISSUE THREAD

**Issue by eitamal** [BigBabay/AsyncConverter#18]
When I tried updating ReSharper to the latest version:

> JetBrains ReSharper Ultimate 2017.2  Build 109.0.20170824.131346
> ReSharper 2017.2.20170824.133358

I got errors during installation which was only fixed after removing the AsyncConverter extension, and when I try to reinstall the extension again I get the same errors once more:
[Syrezos.txt](https://github.com/BigBabay/AsyncConverter/files/1255323/Syrezos.txt)

**Comment by BigBabay** [comment]
Fixed in new 1.1.8.1 version
