### ISSUE TITLE
AsyncAwaitMayBeElidedHighlighting in TestMethods using MSTest

### ISSUE THREAD

**Issue by Sandmann-cs1** [BigBabay/AsyncConverter#19]
Hello
The AsyncConverter wants to remove the async Keyword from the TestMethod if there is only one awaited MethodCall within that TestMethod.

The problem with this is, that MSTest will no longer recognize this TestMethod as a test then.

Here is an example:

```
[TestMethod]
public async Task MyTest()
{
        await MyMethodAsync().ConfigureAwait(false);
}
```

The result would be:

```
[TestMethod]
public Task MyTest()
{
        MyMethodAsync();
}
```

which then will nolonger be recognized as a Test to be run.

Can you Change the rules for this Extension, so that these TestMethods are no longer handled in the current way? Or is there any other possible solution/workaraound, so that the AsyncConverter will no longer Highlights this issue?

Best regards
Christian

**Comment by BigBabay** [comment]
I have added setting for disable AsyncAwaitMayBeElidedHighlighting in test method in version 1.1.8.6
