### ISSUE TITLE
Don't suggest Elide Async/Await unless return types match

### ISSUE THREAD

**Issue by paulirwin** [BigBabay/AsyncConverter#20]
Below is an example where the Elide Async/Await rule appears, but it shouldn't because if you do take that action, it results in invalid code that is a compiler error. Assume `Foo` is a POCO model class and _context is an Entity Framework DbContext with `DbSet<Foo>`. 

```C#
public async Task<IList<Foo>> GetFoosAsync() {
    return await _context.Foos.ToListAsync(); // note: ToListAsync() returns List<Foo> not IList<Foo>
}
```

The highlighting suggestion appears to elide async/await, but if you do that, you get a compiler error that the return types of `Task<IList<Foo>>` and `Task<List<Foo>>` are incompatible, because Task is not covariant.

**Comment by BigBabay** [comment]
Fixed.

**Comment by paulirwin** [comment]
Awesome, thanks! I confirmed this works with the latest version.
