### ISSUE TITLE
AspNetCore remove "Add Async Suffix" quickfix for ControllerBase

### ISSUE THREAD

**Issue by Beviere** [BigBabay/AsyncConverter#21]
In an AspNetCore project the "Add Async Suffix" quickfix is applied to controller actions, when the controller inherits from the ControllerBase. When it inherits from the Controller its works fine. It would be nice to change the check for AspNetCore Controller to ignore that quickfix from "Microsoft.AspNetCore.Mvc.Controller" to "Microsoft.AspNetCore.Mvc.ControllerBase". ControllerBase is the base class of Controller.

**Comment by BigBabay** [comment]
fixed in version 1.1.8.3
