### ISSUE TITLE
Rider IDE support

### ISSUE THREAD

**Issue by olsh** [BigBabay/AsyncConverter#22]
Please port the extension to Rider IDE.
You can find some useful info and examples in the [thread](https://rider-support.jetbrains.com/hc/en-us/community/posts/203460504-ReSharper-extensions?page=1#community_comment_115000493124).

Thank you!

**Comment by BigBabay** [comment]
I have beta version of this. It have some problem with settings. But if you want, try.

[AsyncConverter.AsyncConverter.Rider.zip](https://github.com/BigBabay/AsyncConverter/files/1525830/AsyncConverter.AsyncConverter.Rider.zip)

**Comment by BigBabay** [comment]
Updated version for Rider 2017.3
[AsyncConverter.AsyncConverter.zip](https://github.com/BigBabay/AsyncConverter/files/1623111/AsyncConverter.AsyncConverter.zip)

**Comment by db2222** [comment]
I've tested this updated version with Rider 2017.3.1. I went through all the examples from your page. Everything works fine.

Can you please upload this version in the official Rider plugins repository. Currently there is still a version from 1.12.2017.

Very good work by the way :-)

Thank you!

**Comment by BigBabay** [comment]
Done.
