### ISSUE TITLE
Cannot install in R#2017.3

### ISSUE THREAD

**Issue by dmitrykm** [BigBabay/AsyncConverter#23]
Cannot find in the gallery. Tried offline installation https://resharper-support.jetbrains.com/hc/en-us/articles/207241675-Offline-plug-in-installation-process, but still extension manager does not show the plugin after adding a custom source - a local folder with the plugin. The same offline installation procedure works for another plugin, etherealcode.respeller.4.6.11.3.nupkg, but not for asyncconverter.asyncconverter.1.1.8.3.nupkg:

![image](https://user-images.githubusercontent.com/1682890/34341044-5cf956f8-e9a0-11e7-9463-1a1ea44a801e.png)

![image](https://user-images.githubusercontent.com/1682890/34341053-71be8978-e9a0-11e7-99a5-60ac481744c2.png)

Something is wrong in the packaging of this plugin.

**Comment by BigBabay** [comment]
I have updated plugin to Resharper 2017.3

**Comment by dmitrykm** [comment]
Thanks a lot!
