### ISSUE TITLE
Don't suggest "Async" suffix on methods marked "override"

### ISSUE THREAD

**Issue by Jesse-Hufstetler** [BigBabay/AsyncConverter#25]
When I'm overriding an `async` method from library code (in my case I'm overriding the SignalR `Hub.OnConnected` function) where I can not control the name of the method, I'd like it if AsyncConverter would _not_ suggest that I add the Async suffix (because I can't).

![image](https://user-images.githubusercontent.com/14170257/35686301-fa4b054e-0739-11e8-8b02-1f5bc95765e4.png)

I think the _ideal_ solution would be if the extension could somehow tell if I'm overriding a method that lives in already-compiled code, but something tells me that would be a lot more difficult than just not suggesting the suffix on methods with the `override` keyword (and I'd be happy with that since it would still catch 99% of the instances where I forget the Async suffix)

**Comment by BigBabay** [comment]
fixed in version1.1.8.8
