### ISSUE TITLE
Don't suggest "Add Async Suffix" to async Main methods

### ISSUE THREAD

**Issue by asser-dk** [BigBabay/AsyncConverter#29]
In C# 7 [the `Main` method can now be async](https://blogs.msdn.microsoft.com/mazhou/2017/05/30/c-7-series-part-2-async-main/). However, it still needs to be called `Main` but AsyncConverter suggests you to add the `Async` suffix.

Very minor thing, but those squigglies hurt my eyes ;-)

**Comment by BigBabay** [comment]
fixed in 1.1.8.16
