### ISSUE TITLE
Wrong suggestion to elide the await

### ISSUE THREAD

**Issue by OmiCron07** [BigBabay/AsyncConverter#35]
I have a couple of wrong suggestions to elide the await when I have code after the await : 

![image](https://user-images.githubusercontent.com/31325575/42385272-4ccc0b66-810a-11e8-900c-832a22041cf6.png)

After the fix :

![image](https://user-images.githubusercontent.com/31325575/42385353-86850a2e-810a-11e8-9004-9527ba727e86.png)

**Comment by OmiCron07** [comment]
Any update on this issue?

**Comment by BigBabay** [comment]
fixed in  version 1.1.8.15
