### ISSUE TITLE
Add ReSharper 2019.1 support

### ISSUE THREAD

**Issue by OmiCron07** [BigBabay/AsyncConverter#47]

**Comment by ogazioglu** [comment]
+1

**Comment by elmanav** [comment]
Please. +1

**Comment by kuzyaka** [comment]
+1
@BigBabay 
Is AsyncConverter plugin abandoned?

**Comment by BigBabay** [comment]
Hi. I support plugin, when i have time.
I already updated plugin. It wait jetbrains support approval.

**Comment by BigBabay** [comment]
Done in version 1.1.8.14

**Comment by kuzyaka** [comment]
Does it support Rider 2019.1.1?

**Comment by BigBabay** [comment]
Yes, version 1.1.8.14 (https://plugins.jetbrains.com/plugin/10235-asyncconverter/update/62667) is support Rider 2019.1 — 2019.1.1
