### ISSUE TITLE
Distinguish framework Wait from user-defined Wait

### ISSUE THREAD

**Issue by kuzyaka** [BigBabay/AsyncConverter#48]
![image](https://user-images.githubusercontent.com/8079377/61690463-6e322800-ad3a-11e9-8af0-4d591bafad8b.png)

**Comment by maartenkools** [comment]
Possibly related, but we're getting a false positive on a [ManualResetEventSlim.Wait](https://docs.microsoft.com/en-us/dotnet/api/system.threading.manualreseteventslim.wait?view=netcore-2.2#System_Threading_ManualResetEventSlim_Wait_System_TimeSpan_) call.

**Comment by BigBabay** [comment]
updated
