### ISSUE TITLE
Don't suggest elide await inside async using declaration

### ISSUE THREAD

**Issue by NickLydon** [BigBabay/AsyncConverter#56]
The following code with an async using declaration suggests to elide the await:
```csharp
private static async Task CreateTestFile(string filePath)
{
    await using var fs = File.Create(filePath);
    var info = new UTF8Encoding(true).GetBytes("This is some text in the file.");
    await fs.WriteAsync(info, 0, info.Length).ConfigureAwait(false); // suggests to elide await
}
```
The automatically-refactored code does not compile:
```csharp
private static Task CreateTestFile(string filePath)
{
    await using var fs = File.Create(filePath);
    var info = new UTF8Encoding(true).GetBytes("This is some text in the file.");
    return fs.WriteAsync(info, 0, info.Length);
}
```
The error message is:
>   The 'await' operator can only be used within an async method. Consider marking this method with the 'async' modifier and changing its return type to 'Task<Task>'.

**Comment by ristogod** [comment]
Even worse is when `IAsyncDisposable `isn't an option for the `using`. In that case the refactored code compiles, but at runtime fails because the task is attempted on an already disposed object.

**Comment by BigBabay** [comment]
Fixed in new version
