### ISSUE TITLE
Don't suggest elide await in a method with using declaration represented as variable

### ISSUE THREAD

**Issue by gregzhadko** [BigBabay/AsyncConverter#61]
The plugin suggests to remove async/await in the following code:
```
public async Task<string> GetAsync(string URL)
{
     using var client = new HttpClient();
     return await client.GetStringAsync(url);
}
```
If I apply this refactoring, the `Task` continues execution after calling the `Dispose()` method. It is not correct behavior, and I suggest removing this tip for methods like this.

**Comment by BigBabay** [comment]
Done in new version
