### ISSUE TITLE
The new version has not been released yet?

### ISSUE THREAD

**Issue by YuChia-Wei** [BigBabay/AsyncConverter#79]
The new version PR is finished in 2021/04/18, but JetBrains Marketplace is not updated yet.

**Comment by ristogod** [comment]
Yes, what is the hold up?

**Comment by AndreyRavkov** [comment]
+1

**Comment by ristogod** [comment]
What are the rules and etiquette to branching this repo and releasing a new competing extension that will actually be updated and uploaded in a timely manner?

**Comment by kulakovt** [comment]
@BigBabay , this is a vital extension, please update it!

**Comment by avonwyss** [comment]
> What are the rules and etiquette to branching this repo and releasing a new competing extension that will actually be updated and uploaded in a timely manner?

The license seems to be MIT, so you can do just that without breaching the license. Attribution aside, you should make sure that it has a different name in order to avoid a clash on the JetBrains extensions.
