### ISSUE TITLE
Do not suggest to use obsolete async methods

### ISSUE THREAD

**Issue by cd21h** [BigBabay/AsyncConverter#9]
AsyncConverter should not suggest to use existing async counterpart if async method is marked with *ObsoleteAttribute*.

E.g. in Newtonsoft,Json 9.0.1 followinf method should not be suggested for JsonConverter.SerializeObject

    [Obsolete(...)]
    public static Task<string> SerializeObjectAsync(object value)

**Comment by BigBabay** [comment]
Thanks. I added this functionality.

**Comment by cd21h** [comment]
Thanks!
